export const products = [
  {
    _id: '621235e59540445b3sdfe9s0',
    name: 'Soy Sauce 150 ml',
    image: '/images/img1.jpeg',
    description:
      "Kikkoman Soy Sauce is the classic among soy sauces and one of the best-selling soy sauces in the world.",
    brand: 'KIKKOMAN',
    category: 'Sauce',
    price: 3995,
    rating: 5,
    numReviews: 1,
    isNew: true,
    reviews: [],
    stock: 7,
  },
  {
    _id: '636985e59540445b3c45e6af',
    name: 'Soy Sauce, Less Salt, 150ml',
    image: '/images/img2.jpeg',
    description:
      'Naturally brewed and fermented soy sauce.',
    brand: 'KIKKOMAN',
    category: 'Sauce',
    price: 2490,
    rating: 3,
    numReviews: 1,
    isNew: false,
    reviews: [],
    stock: 5,
  },
  {
    _id: '6369860d9540445b3c45e6b1',
    name: 'Oyster Sauce 150ml',
    image: '/images/img3.jpeg',
    description:
      "Made from authentic oyster extract, intensely salty flavor, and velvet texture, Maekrua creates a handsome brown color and aromatic flavor.",
    brand: 'MAEKRUA',
    category: 'Sauce',
    price: 990,
    countInStock: 11,
    rating: 5,
    numReviews: 0,
    isNew: false,
    reviews: [],
    stock: 0,
  },
  {
    _id: '6369863c9540445b3c45e6b3',
    name: 'Quick fried noodles',
    image: '/images/img4.jpeg',
    description:
      'Chinese pre-cooked egg-noodles with quik preparation VIMIXA 500g.',
    brand: 'VIMIXA',
    category: 'Noodles',
    price: 795,
    rating: 5,
    numReviews: 0,
    isNew: false,
    reviews: [],
    stock: 7,
  },
  {
    _id: '636986579540445b3c45e6b5',
    name: 'Pad Thai Noodles 5mm',
    image: '/images/img5.png',
    description:
      "Most of us want to know more about ourselves, so we can be the best version of ourselves. That's why we engineered the all-new Galaxy Watch4 Classic to be the companion to your journey towards a healthier you.",
    brand: 'Banh Pho',
    category: 'Noodles',
    price: 1090,
    rating: 4,
    numReviews: 1,
    isNew: false,

    reviews: [],
    stock: 1,
  },
  {
    _id: '636986749540445b3c45e6b7',
    name: 'Sriracha chili sauce',
    image: '/images/img6.jpeg',
    description:
      'Thai Chilli Sriracha sauce is suitable for all spicy Asian delicacies. The base consists of hot chili peppers and garlic. The sauce is very popular throughout Asia.',
    brand: 'Flying Goose',
    category: 'Sauce',
    price: 1090,
    rating: 5,
    numReviews: 0,
    isNew: false,
    stock: 0,
  },
  {
    _id: '63804a5079636c2ced47757d',
    name: 'Sriracha-Mayo',
    image: '/images/img7.jpeg',
    brand: 'Flying Goose',
    category: 'Sauce',
    description:
      'Sriracha Mayo Thai Chilli Sauce is suitable for all spicy Asian delicacies. The base consists of mayonnaise, chilli peppers and garlic. The sauce is very popular.',
    rating: 0,
    numReviews: 0,
    price: 1190,
    stock: 5,
    isNew: true,
    reviews: [],
  },
  {
    _id: '6381275e8e8648e00b7c82f7',
    name: 'SSushi Nori roasted seaweed 11g',
    image: '/images/img8.webp',
    brand: 'MAKI',
    category: 'Nori',
    description:
      'Roasted seaweeds, ideal to prepare sushi “MAKI”. Contains 8 sheets (makes around 50 sushis).',
    rating: 0,
    numReviews: 0,
    price: 1390,
    stock: 2,
    isNew: true,
    reviews: [],
  },
  {
    _id: '63895d3b2a3e062504353022',
    name: 'Ice mochi',
    image: '/images/img10.jpeg',
    brand: 'Mochi Ice',
    category: 'Mochi',
    description:
      "Vanilla 156g.",
    rating: 5,
    numReviews: 1,
    price: 1390,
    stock: 49,
    isNew: true,
    reviews: [],
  },
];
